### ISSUE TITLE
its was good

### ISSUE THREAD

**Issue by Vishwas567917** [natsalete/Minhas-Tarefas#1]
i like this one and i also build this one but not the same  and can u tell me what is the usage of this and how it will affect in our real life and one more thing 
do u know how to add flag counter in the profile readme 
because u know i add one in my profile but its only show me two country idk why its show only two country many people form different country also see  my profile 
so can u help me plz

**Comment by natsalete** [comment]
Hello!

I created this repository for training. Its main use in everyday life is to function as an improvement to a notepad, helping you with your daily tasks. You can write down the tasks you need to do and when you complete them, mark them as done.

About how to add a flag counter in the README profile, there are two ways I know:

1. Using Flag Counter:

- Visit [this site](https://flagcounter.com/), which generates a free counter for any web page and collects flags from all over the world. Every time someone from a new country visits your website, a flag will be added to your counter.
- After configuring the counter on the website (defining the number of flags, color, etc.), you will receive a code to insert in your README. For example:

 ```html
<a href="https://info.flagcounter.com/LTZy"><img src="https://s11.flagcounter.com/count2/LTZy/bg_FFFFFF/txt_000000/border_CCCCCC/columns_2/maxflags_10/viewers_0/labels_0/pageviews_0/flags_0/percent_0/" alt="Flag Counter" border="0"></a>

```
- This is just an example, you can edit according to your preferences on the website.

2. Generic Visit Counter:

- This approach only counts profile visits and does not show country flags. Use the following code::
```html
<img width="200px" align="left" src="https://komarev.com/ghpvc/?username=natsalete&style=flat-square&color=22CCB2">

```

- Replace "natsalete" with your GitHub profile name.

Hope this helps! Any doubt I am available.

**Comment by Vishwas567917** [comment]
i add it but its still not working and it show only 2country and when i check other people profile and its show me that they are from china or Russia or brazil 
but its show only 2 usa and india why

**Comment by natsalete** [comment]
So, go back to the website and create a new code to paste into the README. It will start counting from now on, showing only your country's flag with 1 view, which will be you. Paste it into your README and let me know here so I can visit your profile and see if the Brazilian flag appears.

**Comment by Vishwas567917** [comment]
ok sure

**Comment by Vishwas567917** [comment]
done u can check it now

**Comment by natsalete** [comment]
I will check!

**Comment by Vishwas567917** [comment]
so its not worrking at all if u see my profile

**Comment by natsalete** [comment]
It really isn't, I'll add it to my profile to see if it isn't working either

**Comment by Vishwas567917** [comment]
mhm

**Comment by natsalete** [comment]
I added it, you could check it on my profile

**Comment by Vishwas567917** [comment]
its show me error

**Comment by Vishwas567917** [comment]
i think its not working at all 
we should stop it ig

**Comment by Vishwas567917** [comment]
what u think ??

**Comment by natsalete** [comment]
It doesn't really work, I don't know why it must be an error on the website

**Comment by natsalete** [comment]
I agree!

**Comment by Vishwas567917** [comment]
ooo ok same here 
so bye now than

**Comment by natsalete** [comment]
I'll leave it on my profile for a while, because it might take a while to update.

**Comment by Vishwas567917** [comment]
mhm sure

**Comment by natsalete** [comment]
Hello, I'm reopening the conversation because I discovered the error. The views will only be updated when you commit to your README.

**Comment by natsalete** [comment]
If you go to your README and click on edit and then make a commit it will update

**Comment by Vishwas567917** [comment]
yu i get it but i already this
