### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Vishwas567917** [natsalete/Minhas-Tarefas#2]
i want yr help i cant find any better project for me can u suggest me some project when i can make 
i know the html , css , js , tailwind, node.js, ejs, and so on

**Comment by natsalete** [comment]
I know some websites with incredible projects to train on.
1 - Front end Practice (https://www.frontendpractice.com/) - Challenges to improve your front-end skills, recreating real websites from real companies.
2 - App Ideas (Github repositories: https://github.com/florinpop17/app-ideas) - Compiled with challenges for you to test your knowledge and increase your portfolio.
3 - CodePen Challenges (https://codepen.io/challenges) - Front-end Programming Challenges.
4- DevChallenge(https://www.devchallenge.com.br/) - Site with front-end, back-end and mobile challenges.

I hope some of these can help you.

**Comment by Vishwas567917** [comment]
can u suggest some more
